version: "3.8"
name: pdf-extractor

services:
  api:
    build: ./api
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: "pdf_extractor"
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - database
    volumes:
      - ./api:/api
    networks:
      - pdf-extractor-network
  database:
    build: ./docker/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql/postgresql.conf.sample:/usr/share/postgresql/postgresql.conf.sample
      - ./docker/postgresql/db_init.sql:/docker-entrypoint-initdb.d/db_init_init.sql
      - postgres:/var/lib/postgresql/data
    networks:
      - pdf-extractor-network
networks:
  pdf-extractor-network:
    driver: bridge

volumes:
  postgres: