version: "3.8"
name: pdf-extract

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdf_extract
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
